// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieDatabaseContext))]
    [Migration("20220123221548_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Drama",
                            Director = "Stephen Spielberg",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Catch Me If You Can",
                            Year = 2002
                        },
                        new
                        {
                            Id = 2,
                            Category = "Thriller/Mystery",
                            Director = "Louis Leterrier",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Now You See Me",
                            Year = 2013
                        },
                        new
                        {
                            Id = 3,
                            Category = "Romance/Adventure",
                            Director = "Clive Donner",
                            Edited = false,
                            Rating = "PG",
                            Title = "The Scarlet Pimpernel",
                            Year = 1982
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
